### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [Epskampie/sublime_indent_and_braces#1]
Hi. Would be good to see for Synwrite too
https://sourceforge.net/p/synwrite/wiki/python%20API/
Other api, but possible of course

**Comment by Epskampie** [comment]
Hi Alexey, thanks for you suggestion. However, I've check out synwrite, and at this time I'm not interested in supporting it.

**Comment by Alexey-T** [comment]
Is it easy to refactor? eg make `def` which gets N lines affected by selection (list of str), makes N+2 lines from them (with additional {} and space)

**Comment by Epskampie** [comment]
At this point it isn't, as it needs to know stuff like the current
indentation. However, the whole plugin is just 50 lines, so it can't be
hard to port if your python API is really similar.

https://github.com/Epskampie/sublime_indent_and_braces/blob/master/indent-and-braces.py

I would do it myself, but like i said, at this point I don't like synwrite
enough to do it. I don't want to be too harsh, but it seems like your
editor, while decent, doesn't really have any advantages over other efforts
like notepad++. You should really try to make give your editor a killer
feature, like for example: sublime is really fast and cross-platform and
has multiple cursor support, notepad++ is open-source and free, etc. Your
editor seems so far to just "copy what others do", but that is not good
enough, it needs to improve upon the status quo in some way before i'd
consider spending time on it.

**Comment by Alexey-T** [comment]
talking about Synw, I must say IT DOES have features. over Notepad++. e.g.--see lexer configuration.

**Comment by Epskampie** [comment]
Sorry, but for me that is not a killer feature.

**Comment by Alexey-T** [comment]
btw. Synw now has "CBlock" plugin. (In addons manager)

**Comment by Epskampie** [comment]
Ok, nice work! I've quickly tested it, and it seems to work fine.

Best of luck with the future development of synwrite.
