### ISSUE TITLE
Wraps before starting line, even when beginning of selection is the middle

### ISSUE THREAD

**Issue by raineorshine** [Epskampie/sublime_indent_and_braces#3]
I find it confusing that the character position of the selection is not used as the point of insertion, but rather the entire line.

Given the following selection (start and end points indicated with `|`:

```
var deps = |{
    bluebird: '^2.9.27',
    commander: '~2.8.1',
    lodash: '^3.2.0',
}|;
```

I would expect this (which only requires me adding the key):

```
var deps = {
    {
        bluebird: '^2.9.27',
        commander: '~2.8.1',
        lodash: '^3.2.0',
    }
};
```

But instead I get this:

```
{
    var deps = {
        async: '^0.9.0',
        bluebird: '^2.9.27',
        cint: '^8.2.1',
        commander: '~2.8.1',
        lodash: '^3.2.0',
    };
}
```

If I had wanted the entire block to be included, I would have selected the entire block to begin with. Perhaps that was the use case that was intended originally with this plugin, but I think it could be improved to support both.

Strangely, when the start of the selection is at the end of the line, it does what I want (granted without the initial newline).

```
var deps = {{
        async: '^0.9.0',
        bluebird: '^2.9.27',
        cint: '^8.2.1',
        commander: '~2.8.1',
        lodash: '^3.2.0',
    };
}
```

I might be able to do a pull request, but let me know if this makes sense or if you can implement it.

**Comment by Epskampie** [comment]
Hi Metaraine,

Thanks for your remarks. If you use the following selection instead:

```
var deps = {
    |bluebird: '^2.9.27',
    commander: '~2.8.1',
    lodash: '^3.2.0',|
};
```

You get the desired result. The start/end positions can be anywhere on those lines. 

The current behaviour is designed this way to allow you to easily wrap multiple lines in a {} block, without having to be too careful. I think this is exacly what you want, you just need to select the lines you want to wrap, which seems logical to me. 

There is a special case when your selection starts on the end of a line, which is the `if (foo) {|` case.

If you've got a good idea how to solve all these cases and yours as well, I welcome pull requests.

**Comment by raineorshine** [comment]
Thanks, I will see how the plugin fares for me and give it some thought :)
